name: fxendit
description: The easy way to use Xendit Software Development Kit (SDK) in Flutter.
version: 0.0.3
# author: Salman S
homepage: https://github.com/salkuadrat/fxendit
repository: https://github.com/salkuadrat/fxendit

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.xendit.fxendit
        pluginClass: FxenditPlugin
